import type {
	ListingCategoryMeta,
	ListingResponse,
} from "@/domains/listings/dto/listing-view";

const image = (url: string) => ({ imageId: url, url });

export const mockListings: ListingResponse[] = [
	{
		id: "prod-001",
		name: "American Professional II Stratocaster",
		brand: "Fender",
		model: "Stratocaster",
		category: "ELECTRIC",
		condition: "MINT",
		priceAmountMinor: 169999,
		currencyCode: "TWD",
		images: [image("/placeholder-guitar.jpg")],
		description: "",
		stock: 1,
		isApproved: true,
		sellerId: "user-001",
		seller: { firstName: "VintageBoxes", lastName: "", email: "" },
	},
	{
		id: "prod-002",
		name: "Les Paul Standard '60s",
		brand: "Gibson",
		model: "Les Paul",
		category: "ELECTRIC",
		condition: "USED",
		priceAmountMinor: 229900,
		currencyCode: "TWD",
		images: [image("/placeholder-guitar.jpg")],
		description: "",
		stock: 1,
		isApproved: true,
		sellerId: "user-002",
		seller: { firstName: "ToneHunter", lastName: "", email: "" },
	},
	{
		id: "prod-003",
		name: "D-28 Standard Dreadnought",
		brand: "Martin",
		model: "D-28",
		category: "ACOUSTIC",
		condition: "NEW",
		priceAmountMinor: 319900,
		currencyCode: "TWD",
		images: [image("/placeholder-acoustic.jpg")],
		description: "",
		stock: 1,
		isApproved: true,
		sellerId: "user-003",
		seller: { firstName: "AcousticPro", lastName: "", email: "" },
	},
	{
		id: "prod-004",
		name: "Taylor 814ce Builder's Edition",
		brand: "Taylor",
		model: "814ce",
		category: "ACOUSTIC",
		condition: "MINT",
		priceAmountMinor: 399900,
		currencyCode: "TWD",
		images: [image("/placeholder-acoustic.jpg")],
		description: "",
		stock: 1,
		isApproved: true,
		sellerId: "user-004",
		seller: { firstName: "StringTheory", lastName: "", email: "" },
	},
	{
		id: "prod-005",
		name: "Nord Stage 4 88",
		brand: "Nord",
		model: "Stage 4",
		category: "KEYBOARD",
		condition: "NEW",
		priceAmountMinor: 549900,
		currencyCode: "TWD",
		images: [image("/placeholder-keyboard.jpg")],
		description: "",
		stock: 1,
		isApproved: true,
		sellerId: "user-005",
		seller: { firstName: "KeysKing", lastName: "", email: "" },
	},
	{
		id: "prod-006",
		name: "Prophet Rev2 16-Voice",
		brand: "Sequential",
		model: "Prophet Rev2",
		category: "KEYBOARD",
		condition: "USED",
		priceAmountMinor: 189900,
		currencyCode: "TWD",
		images: [image("/placeholder-keyboard.jpg")],
		description: "",
		stock: 1,
		isApproved: true,
		sellerId: "user-006",
		seller: { firstName: "SynthLab", lastName: "", email: "" },
	},
	{
		id: "prod-007",
		name: "Tube Screamer TS9",
		brand: "Ibanez",
		model: "TS9",
		category: "ACCESSORY",
		condition: "NEW",
		priceAmountMinor: 9999,
		currencyCode: "TWD",
		images: [image("/placeholder-pedal.jpg")],
		description: "",
		stock: 1,
		isApproved: true,
		sellerId: "user-007",
		seller: { firstName: "PedalBoard", lastName: "", email: "" },
	},
	{
		id: "prod-008",
		name: "SM58 Dynamic Microphone",
		brand: "Shure",
		model: "SM58",
		category: "ACCESSORY",
		condition: "MINT",
		priceAmountMinor: 9900,
		currencyCode: "TWD",
		images: [image("/placeholder-mic.jpg")],
		description: "",
		stock: 1,
		isApproved: true,
		sellerId: "user-008",
		seller: { firstName: "SoundGear", lastName: "", email: "" },
	},
	{
		id: "prod-009",
		name: "Player Telecaster",
		brand: "Fender",
		model: "Telecaster",
		category: "ELECTRIC",
		condition: "NEW",
		priceAmountMinor: 84999,
		currencyCode: "TWD",
		images: [image("/placeholder-guitar.jpg")],
		description: "",
		stock: 1,
		isApproved: true,
		sellerId: "user-009",
		seller: { firstName: "GuitarZone", lastName: "", email: "" },
	},
	{
		id: "prod-010",
		name: "Classical Guitar C40",
		brand: "Yamaha",
		model: "C40",
		category: "ACOUSTIC",
		condition: "USED",
		priceAmountMinor: 14999,
		currencyCode: "TWD",
		images: [image("/placeholder-acoustic.jpg")],
		description: "",
		stock: 1,
		isApproved: true,
		sellerId: "user-010",
		seller: { firstName: "BudgetBeats", lastName: "", email: "" },
	},
	{
		id: "prod-011",
		name: "Minilogue XD",
		brand: "Korg",
		model: "Minilogue XD",
		category: "KEYBOARD",
		condition: "MINT",
		priceAmountMinor: 64900,
		currencyCode: "TWD",
		images: [image("/placeholder-keyboard.jpg")],
		description: "",
		stock: 1,
		isApproved: true,
		sellerId: "user-011",
		seller: { firstName: "AnalogDreams", lastName: "", email: "" },
	},
	{
		id: "prod-012",
		name: "Big Muff Pi",
		brand: "Electro-Harmonix",
		model: "Big Muff",
		category: "ACCESSORY",
		condition: "USED",
		priceAmountMinor: 7900,
		currencyCode: "TWD",
		images: [image("/placeholder-pedal.jpg")],
		description: "",
		stock: 1,
		isApproved: true,
		sellerId: "user-012",
		seller: { firstName: "FuzzFactory", lastName: "", email: "" },
	},
];

export const mockCategories: ListingCategoryMeta[] = [
	{
		category: "ELECTRIC",
		label: "Electric Guitars",
		icon: "Zap",
		count: 156,
	},
	{
		category: "ACOUSTIC",
		label: "Acoustic Guitars",
		icon: "Music",
		count: 89,
	},
	{
		category: "KEYBOARD",
		label: "Keyboards & Synths",
		icon: "Piano",
		count: 64,
	},
	{
		category: "ACCESSORY",
		label: "Accessories",
		icon: "Mic2",
		count: 234,
	},
];

export const featuredListings = mockListings.slice(0, 4);
export const recentListings = mockListings.slice(4, 10);
