import type { CategoryMeta, Product } from "@/types/product";

export const mockProducts: Product[] = [
	{
		id: "prod-001",
		name: "American Professional II Stratocaster",
		brand: "Fender",
		model: "Stratocaster",
		category: "ELECTRIC",
		condition: "mint",
		price: 1699.99,
		image: "/placeholder-guitar.jpg",
		sellerId: "user-001",
		sellerName: "VintageAxes",
	},
	{
		id: "prod-002",
		name: "Les Paul Standard '60s",
		brand: "Gibson",
		model: "Les Paul",
		category: "ELECTRIC",
		condition: "used",
		price: 2299.0,
		image: "/placeholder-guitar.jpg",
		sellerId: "user-002",
		sellerName: "ToneHunter",
	},
	{
		id: "prod-003",
		name: "D-28 Standard Dreadnought",
		brand: "Martin",
		model: "D-28",
		category: "ACOUSTIC",
		condition: "new",
		price: 3199.0,
		image: "/placeholder-acoustic.jpg",
		sellerId: "user-003",
		sellerName: "AcousticPro",
	},
	{
		id: "prod-004",
		name: "Taylor 814ce Builder's Edition",
		brand: "Taylor",
		model: "814ce",
		category: "ACOUSTIC",
		condition: "mint",
		price: 3999.0,
		image: "/placeholder-acoustic.jpg",
		sellerId: "user-004",
		sellerName: "StringTheory",
	},
	{
		id: "prod-005",
		name: "Nord Stage 4 88",
		brand: "Nord",
		model: "Stage 4",
		category: "KEYBOARD",
		condition: "new",
		price: 5499.0,
		image: "/placeholder-keyboard.jpg",
		sellerId: "user-005",
		sellerName: "KeysKing",
	},
	{
		id: "prod-006",
		name: "Prophet Rev2 16-Voice",
		brand: "Sequential",
		model: "Prophet Rev2",
		category: "KEYBOARD",
		condition: "used",
		price: 1899.0,
		image: "/placeholder-keyboard.jpg",
		sellerId: "user-006",
		sellerName: "SynthLab",
	},
	{
		id: "prod-007",
		name: "Tube Screamer TS9",
		brand: "Ibanez",
		model: "TS9",
		category: "ACCESSORY",
		condition: "new",
		price: 99.99,
		image: "/placeholder-pedal.jpg",
		sellerId: "user-007",
		sellerName: "PedalBoard",
	},
	{
		id: "prod-008",
		name: "SM58 Dynamic Microphone",
		brand: "Shure",
		model: "SM58",
		category: "ACCESSORY",
		condition: "mint",
		price: 99.0,
		image: "/placeholder-mic.jpg",
		sellerId: "user-008",
		sellerName: "SoundGear",
	},
	{
		id: "prod-009",
		name: "Player Telecaster",
		brand: "Fender",
		model: "Telecaster",
		category: "ELECTRIC",
		condition: "new",
		price: 849.99,
		image: "/placeholder-guitar.jpg",
		sellerId: "user-009",
		sellerName: "GuitarZone",
	},
	{
		id: "prod-010",
		name: "Classical Guitar C40",
		brand: "Yamaha",
		model: "C40",
		category: "ACOUSTIC",
		condition: "used",
		price: 149.99,
		image: "/placeholder-acoustic.jpg",
		sellerId: "user-010",
		sellerName: "BudgetBeats",
	},
	{
		id: "prod-011",
		name: "Minilogue XD",
		brand: "Korg",
		model: "Minilogue XD",
		category: "KEYBOARD",
		condition: "mint",
		price: 649.0,
		image: "/placeholder-keyboard.jpg",
		sellerId: "user-011",
		sellerName: "AnalogDreams",
	},
	{
		id: "prod-012",
		name: "Big Muff Pi",
		brand: "Electro-Harmonix",
		model: "Big Muff",
		category: "ACCESSORY",
		condition: "used",
		price: 79.0,
		image: "/placeholder-pedal.jpg",
		sellerId: "user-012",
		sellerName: "FuzzFactory",
	},
];

export const mockCategories: CategoryMeta[] = [
	{
		category: "ELECTRIC",
		label: "Electric Guitars",
		icon: "Zap",
		count: 156,
	},
	{
		category: "ACOUSTIC",
		label: "Acoustic Guitars",
		icon: "Music",
		count: 89,
	},
	{
		category: "KEYBOARD",
		label: "Keyboards & Synths",
		icon: "Piano",
		count: 64,
	},
	{
		category: "ACCESSORY",
		label: "Accessories",
		icon: "Mic2",
		count: 234,
	},
];

export const featuredProducts = mockProducts.slice(0, 4);
export const recentProducts = mockProducts.slice(4, 10);
