/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ShopRouteRouteImport } from './routes/shop/route'
import { Route as SettingsRouteRouteImport } from './routes/settings/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShopIndexRouteImport } from './routes/shop/index'
import { Route as ReviewsIndexRouteImport } from './routes/reviews/index'
import { Route as ListingNewRouteImport } from './routes/listing/new'
import { Route as ListingIdRouteImport } from './routes/listing/$id'
import { Route as ListingEditIdRouteImport } from './routes/listing/edit.$id'

const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRouteRoute = ShopRouteRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRouteRoute = SettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopIndexRoute = ShopIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShopRouteRoute,
} as any)
const ReviewsIndexRoute = ReviewsIndexRouteImport.update({
  id: '/reviews/',
  path: '/reviews/',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingNewRoute = ListingNewRouteImport.update({
  id: '/listing/new',
  path: '/listing/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingIdRoute = ListingIdRouteImport.update({
  id: '/listing/$id',
  path: '/listing/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingEditIdRoute = ListingEditIdRouteImport.update({
  id: '/listing/edit/$id',
  path: '/listing/edit/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRouteRoute
  '/shop': typeof ShopRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/community': typeof CommunityRoute
  '/notifications': typeof NotificationsRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/listing/$id': typeof ListingIdRoute
  '/listing/new': typeof ListingNewRoute
  '/reviews': typeof ReviewsIndexRoute
  '/shop/': typeof ShopIndexRoute
  '/listing/edit/$id': typeof ListingEditIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRouteRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/community': typeof CommunityRoute
  '/notifications': typeof NotificationsRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/listing/$id': typeof ListingIdRoute
  '/listing/new': typeof ListingNewRoute
  '/reviews': typeof ReviewsIndexRoute
  '/shop': typeof ShopIndexRoute
  '/listing/edit/$id': typeof ListingEditIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings': typeof SettingsRouteRoute
  '/shop': typeof ShopRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/community': typeof CommunityRoute
  '/notifications': typeof NotificationsRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/listing/$id': typeof ListingIdRoute
  '/listing/new': typeof ListingNewRoute
  '/reviews/': typeof ReviewsIndexRoute
  '/shop/': typeof ShopIndexRoute
  '/listing/edit/$id': typeof ListingEditIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/shop'
    | '/about'
    | '/cart'
    | '/checkout'
    | '/community'
    | '/notifications'
    | '/unauthorized'
    | '/listing/$id'
    | '/listing/new'
    | '/reviews'
    | '/shop/'
    | '/listing/edit/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings'
    | '/about'
    | '/cart'
    | '/checkout'
    | '/community'
    | '/notifications'
    | '/unauthorized'
    | '/listing/$id'
    | '/listing/new'
    | '/reviews'
    | '/shop'
    | '/listing/edit/$id'
  id:
    | '__root__'
    | '/'
    | '/settings'
    | '/shop'
    | '/about'
    | '/cart'
    | '/checkout'
    | '/community'
    | '/notifications'
    | '/unauthorized'
    | '/listing/$id'
    | '/listing/new'
    | '/reviews/'
    | '/shop/'
    | '/listing/edit/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRouteRoute: typeof SettingsRouteRoute
  ShopRouteRoute: typeof ShopRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  CommunityRoute: typeof CommunityRoute
  NotificationsRoute: typeof NotificationsRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
  ListingIdRoute: typeof ListingIdRoute
  ListingNewRoute: typeof ListingNewRoute
  ReviewsIndexRoute: typeof ReviewsIndexRoute
  ListingEditIdRoute: typeof ListingEditIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/': {
      id: '/shop/'
      path: '/'
      fullPath: '/shop/'
      preLoaderRoute: typeof ShopIndexRouteImport
      parentRoute: typeof ShopRouteRoute
    }
    '/reviews/': {
      id: '/reviews/'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listing/new': {
      id: '/listing/new'
      path: '/listing/new'
      fullPath: '/listing/new'
      preLoaderRoute: typeof ListingNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listing/$id': {
      id: '/listing/$id'
      path: '/listing/$id'
      fullPath: '/listing/$id'
      preLoaderRoute: typeof ListingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listing/edit/$id': {
      id: '/listing/edit/$id'
      path: '/listing/edit/$id'
      fullPath: '/listing/edit/$id'
      preLoaderRoute: typeof ListingEditIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ShopRouteRouteChildren {
  ShopIndexRoute: typeof ShopIndexRoute
}

const ShopRouteRouteChildren: ShopRouteRouteChildren = {
  ShopIndexRoute: ShopIndexRoute,
}

const ShopRouteRouteWithChildren = ShopRouteRoute._addFileChildren(
  ShopRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRouteRoute: SettingsRouteRoute,
  ShopRouteRoute: ShopRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  CommunityRoute: CommunityRoute,
  NotificationsRoute: NotificationsRoute,
  UnauthorizedRoute: UnauthorizedRoute,
  ListingIdRoute: ListingIdRoute,
  ListingNewRoute: ListingNewRoute,
  ReviewsIndexRoute: ReviewsIndexRoute,
  ListingEditIdRoute: ListingEditIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
